org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

mod_id = eof
mod_name = Echoes of Factoria
mod_version = 1.0.0
mod_description = A mod that tries to make Minecraft into a factory simulator. It adds new machines, items, and blocks to automate resource gathering and processing.
mod_authors = asunacraft
mod_license = MIT License (Assets: CC BY-NC-SA 4.0)
mod_url = https://github.com/asunacraft/echoes-of-factoria/
mod_issue_tracker = https://github.com/asunacraft/echoes-of-factoria/issues/
maven_group = net.asunacraft.eof

forge_version_range = [47,)
loader_version_range = [47,)